name: Check source code correctness

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  texbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Make docs/ directory
        run: mkdir docs/
      - name: Compile LaTeX document
        uses: birjolaxew/tectonic-biber-action@master
        with:
          files: "report/report.tex"
          tectonic_args: "-o docs/"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "docs/"

  sqlcheck:
    name: sqlcheck job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: yokawasa/action-sqlcheck@v1.4.0
      with:
        post-comment: true
        risk-level: 3
        verbose: true
        token: ${{ secrets.GITHUB_TOKEN }}
