name: Check source code correctness

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Make docs/ directory
        run: mkdir docs/
      - name: Compile LaTeX document
        uses: birjolaxew/tectonic-biber-action@master
        with:
          files: "report/report.tex"
          tectonic_args: "-o docs/"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "docs/"
